-- ==============================================================================
-- CAMERA FISCAL SMART AI — PROGRAMA COMPLETO CONSOLIDADO (SCHEMA & MOTOR FISCAL)
-- Referência unificada dos 45 Blocos integrados do banco de dados Supabase (PostgreSQL)
-- ==============================================================================

-- 1. TENANTS, USUÁRIOS E RBAC (Blocos A, B, C, D)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome_fantasia TEXT NOT NULL,
  razao_social TEXT,
  cnpj TEXT UNIQUE,
  tipo_tenant TEXT NOT NULL DEFAULT 'Escritorio',
  plano_id UUID,
  status TEXT NOT NULL DEFAULT 'Ativo',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS usuarios_perfil (
  id UUID PRIMARY KEY,
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  nome_completo TEXT NOT NULL,
  email TEXT NOT NULL,
  papel TEXT NOT NULL DEFAULT 'Analista',
  ativo BOOLEAN DEFAULT true,
  ultimo_login TIMESTAMPTZ,
  ip_ultimo_acesso TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS empresas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  razao_social TEXT NOT NULL,
  nome_fantasia TEXT,
  cnpj TEXT NOT NULL,
  regime_tributario TEXT NOT NULL DEFAULT 'Simples Nacional',
  aliquota_efetiva_simples NUMERIC(10,4),
  uf TEXT,
  municipio_codigo_ibge TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, cnpj)
);

CREATE TABLE IF NOT EXISTS documentos_fiscais (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id),
  tipo_documento TEXT NOT NULL, -- 'NF-e', 'NFC-e', 'CT-e', 'MDF-e'
  chave_acesso CHAR(44),
  origem_captura TEXT DEFAULT 'Upload',
  cnpj_emitente TEXT,
  cnpj_destinatario TEXT,
  tipo_operacao TEXT CHECK (tipo_operacao IN ('entrada', 'saida', 'indefinido')),
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, chave_acesso)
);

CREATE TABLE IF NOT EXISTS lotes_documentos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id),
  status TEXT NOT NULL DEFAULT 'Pendente',
  total_itens INT DEFAULT 0,
  total_divergencias INT DEFAULT 0,
  percentual_conformidade NUMERIC(5,2) DEFAULT 0,
  processamento_iniciado_em TIMESTAMPTZ,
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS itens_nota_auditados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id UUID NOT NULL REFERENCES lotes_documentos(id) ON DELETE CASCADE,
  documento_id UUID REFERENCES documentos_fiscais(id) ON DELETE SET NULL,
  nome_produto VARCHAR(255),
  valor_item NUMERIC(14,2) DEFAULT 0,
  ncm_original TEXT, ncm_correto TEXT,
  cfop_original TEXT, cfop_correto TEXT,
  cst_original TEXT, cst_correto TEXT,
  csosn_original TEXT, csosn_correto TEXT,
  alerta_divergencia BOOLEAN DEFAULT false,
  justificativa_ia TEXT,
  aliquota_ibs_correta NUMERIC(10,4) DEFAULT 0,
  aliquota_cbs_correta NUMERIC(10,4) DEFAULT 0,
  imposto_seletivo_aplicavel BOOLEAN DEFAULT false
);

-- 2. FUNÇÕES DO MOTOR TRIBUTÁRIO (Simples, MEI, Presumido, Real, DIFAL, ICMS-ST, Retenções, ISS)
-- ------------------------------------------------------------------------------

-- [BLOCO 2/3] Cálculo do Simples Nacional com Fator R
-- Formula: Alíquota Efetiva = ((RBT12 * Aliquota Nominal) - Parcela a Deduzir) / RBT12
CREATE OR REPLACE FUNCTION fn_calcular_simples_nacional(
  p_anexo TEXT,
  p_receita_bruta_12m NUMERIC,
  p_valor_nota NUMERIC,
  p_empresa_id UUID DEFAULT null,
  p_folha_pagamento_12m NUMERIC DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true,
  p_cfop TEXT DEFAULT null
) RETURNS JSONB ...

-- [BLOCO 6] Cálculo do MEI (Limites anuais de faturamento, proporcionalidade)
CREATE OR REPLACE FUNCTION fn_calcular_mei(
  p_empresa_id UUID,
  p_competencia DATE,
  p_tipo_atividade TEXT,
  p_receita_mes NUMERIC,
  p_data_abertura DATE,
  p_receita_acumulada_ano NUMERIC,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true
) RETURNS JSONB ...

-- [BLOCO 7/12] Cálculo do Lucro Presumido (IRPJ + adicional, CSLL, PIS, COFINS, ISS, ICMS)
CREATE OR REPLACE FUNCTION fn_calcular_lucro_presumido(
  p_empresa_id UUID,
  p_competencia DATE,
  p_tipo_atividade TEXT,
  p_receita_bruta_mes NUMERIC,
  p_e_venda_produto BOOLEAN,
  p_uf_origem CHAR(2) DEFAULT null,
  p_uf_destino CHAR(2) DEFAULT null,
  p_aliquota_iss NUMERIC DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true
) RETURNS JSONB ...

-- [BLOCO 8] Cálculo do Lucro Real (Ajustes Fiscais, Compensação Prejuízos trava dos 30%, PIS/COFINS não-cumulativos)
CREATE OR REPLACE FUNCTION fn_calcular_lucro_real(
  p_empresa_id UUID,
  p_periodo_inicio DATE,
  p_periodo_fim DATE,
  p_lucro_contabil_informado NUMERIC,
  p_receita_bruta_periodo NUMERIC,
  p_adicoes_irpj NUMERIC DEFAULT 0, p_exclusoes_irpj NUMERIC DEFAULT 0,
  p_adicoes_csll NUMERIC DEFAULT 0, p_exclusoes_csll NUMERIC DEFAULT 0,
  p_prejuizo_fiscal_acumulado_anterior NUMERIC DEFAULT 0,
  p_debito_pis NUMERIC DEFAULT null,
  p_credito_pis NUMERIC DEFAULT 0,
  p_debito_cofins NUMERIC DEFAULT null,
  p_credito_cofins NUMERIC DEFAULT 0,
  p_informado_por UUID DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true
) RETURNS JSONB ...

-- [BLOCO 9/28/35] Cálculo do DIFAL & ICMS-ST (MVA ajustado interestadual, base dupla, FECP RJ/AL, etc.)
CREATE OR REPLACE FUNCTION fn_calcular_difal(
  p_empresa_id UUID,
  p_uf_origem CHAR(2),
  p_uf_destino CHAR(2),
  p_valor_operacao NUMERIC,
  p_e_consumidor_final_nao_contribuinte BOOLEAN,
  p_documento_id UUID DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true,
  p_usar_base_dupla BOOLEAN DEFAULT false
) RETURNS JSONB ...

CREATE OR REPLACE FUNCTION fn_calcular_icms_st(
  p_empresa_id UUID,
  p_ncm TEXT,
  p_cest TEXT,
  p_uf_destino CHAR(2),
  p_valor_produto NUMERIC,
  p_icms_proprio_debito NUMERIC,
  p_ipi_valor NUMERIC DEFAULT 0,
  p_frete_valor NUMERIC DEFAULT 0,
  p_outras_despesas NUMERIC DEFAULT 0,
  p_mva_manual NUMERIC DEFAULT null,
  p_uf_origem CHAR(2) DEFAULT null,
  p_documento_id UUID DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true
) RETURNS JSONB ...

-- [BLOCO 30] Retenções Federais na Fonte (CSRF 4,65% e IRRF 1,5%)
CREATE OR REPLACE FUNCTION fn_calcular_retencao_federal_servico(
  p_valor_servico NUMERIC,
  p_prestador_optante_simples BOOLEAN DEFAULT false,
  p_servico_sujeito_csrf BOOLEAN DEFAULT true,
  p_servico_sujeito_irrf_1_5 BOOLEAN DEFAULT false
) RETURNS JSONB ...

-- [BLOCO 31] ISS Municipal & Limites Constitucionais (2% a 5% pela LC 116/2003)
CREATE OR REPLACE FUNCTION fn_validar_aliquota_iss(
  p_aliquota NUMERIC,
  p_codigo_servico_lc116 TEXT DEFAULT null
) RETURNS JSONB ...

-- [BLOCO 32] Retenção de INSS (Cessão de mão de obra, 11% padrão, 3,5% MEI)
CREATE OR REPLACE FUNCTION fn_calcular_retencao_inss_cessao_mao_obra(
  p_valor_bruto_nota NUMERIC,
  p_prestador_optante_simples BOOLEAN DEFAULT false,
  p_servico_anexo_iv_lc123 BOOLEAN DEFAULT false,
  p_prestador_e_mei BOOLEAN DEFAULT false,
  p_valor_materiais_equipamentos_deduzir NUMERIC DEFAULT 0
) RETURNS JSONB ...

-- [BLOCO 37] Suíte de Testes Automatizada do Motor Fiscal
CREATE OR REPLACE FUNCTION fn_rodar_testes_motor_fiscal()
RETURNS TABLE (
  teste TEXT,
  esperado TEXT,
  obtido TEXT,
  passou BOOLEAN
) ...
