-- ==============================================================================
-- CAMERA FISCAL SMART AI — SCRIPT SQL UNIFICADO CONSOLIDADO (VERSÃO FINAL COMPLETA)
-- Schema Base + 45 Blocos do Motor Tributário em Ordem de Execução
-- Compatível com Supabase (PostgreSQL 15+ / PostGIS / pg_net / pg_cron)
-- ==============================================================================

-- EXTENSÕES REQUERIDAS
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

-- ==============================================================================
-- PARTE 0: CONFIGURAÇÕES E PARÂMETROS GLOBAIS DO SISTEMA
-- ==============================================================================

CREATE TABLE IF NOT EXISTS configuracoes_sistema (
  chave TEXT PRIMARY KEY,
  valor TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'texto' CHECK (tipo IN ('texto', 'numero', 'booleano', 'json')),
  descricao TEXT,
  editavel_por_tenant BOOLEAN DEFAULT false,
  atualizado_em TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- PARTE 1: SCHEMA BASE (TENANTS, USUÁRIOS, RBAC, COMPLIANCE)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome_fantasia TEXT NOT NULL,
  razao_social TEXT,
  cnpj TEXT UNIQUE,
  tipo_tenant TEXT NOT NULL DEFAULT 'Escritorio',
  plano_id UUID,
  status TEXT NOT NULL DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Inativo', 'Suspenso')),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS planos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  preco_mensal NUMERIC(10,2) NOT NULL DEFAULT 0,
  limite_lotes_mes INT,
  limite_creditos_ia INT,
  permite_split_payment BOOLEAN DEFAULT false,
  lock_timeout_minutos INT NOT NULL DEFAULT 10,
  ativo BOOLEAN DEFAULT true
);

-- Adiciona FK de plano em tenants de forma idempotente
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_tenants_plano'
  ) THEN
    ALTER TABLE tenants ADD CONSTRAINT fk_tenants_plano 
      FOREIGN KEY (plano_id) REFERENCES planos(id) ON DELETE SET NULL;
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS usuarios_perfil (
  id UUID PRIMARY KEY,
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  nome_completo TEXT NOT NULL,
  email TEXT NOT NULL,
  papel TEXT NOT NULL DEFAULT 'Analista' CHECK (papel IN ('Dono', 'Gerente', 'Analista', 'Cliente')),
  ativo BOOLEAN DEFAULT true,
  ultimo_login TIMESTAMPTZ,
  ip_ultimo_acesso TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS convites_usuario (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  email_convidado TEXT NOT NULL,
  papel_destino TEXT NOT NULL DEFAULT 'Analista',
  token TEXT NOT NULL UNIQUE,
  expira_em TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '48 hours'),
  aceito BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auditoria_alteracoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID,
  usuario_id UUID,
  tabela_afetada TEXT NOT NULL,
  registro_id TEXT NOT NULL,
  dados_antes JSONB,
  dados_depois JSONB,
  operacao TEXT NOT NULL,
  criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS acessos_falhos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_tentativa TEXT,
  ip TEXT,
  geolocalizacao TEXT,
  navegador TEXT,
  criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assinaturas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  plano_id UUID REFERENCES planos(id),
  status TEXT NOT NULL DEFAULT 'Ativa',
  gateway TEXT DEFAULT 'Asaas',
  gateway_subscription_id TEXT,
  data_inicio TIMESTAMPTZ DEFAULT now(),
  data_proxima_cobranca TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS consumo_creditos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  lote_id UUID,
  creditos_ia_usados NUMERIC(10,4) DEFAULT 0,
  creditos_ocr_usados NUMERIC(10,4) DEFAULT 0,
  criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cotacoes_moedas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moeda TEXT NOT NULL DEFAULT 'USD',
  valor_brl NUMERIC(10,4) NOT NULL,
  data DATE NOT NULL DEFAULT current_date,
  fonte TEXT DEFAULT 'AwesomeAPI',
  criado_em TIMESTAMPTZ DEFAULT now(),
  UNIQUE (moeda, data)
);

CREATE TABLE IF NOT EXISTS lgpd_consentimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios_perfil(id) ON DELETE CASCADE,
  aceite_termos BOOLEAN DEFAULT false,
  aceite_cookies BOOLEAN DEFAULT false,
  ip TEXT,
  criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auditoria_login (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios_perfil(id) ON DELETE SET NULL,
  tenant_id UUID REFERENCES tenants(id) ON DELETE SET NULL,
  evento TEXT NOT NULL CHECK (evento IN ('login_sucesso', 'login_falha', 'logout')),
  ip TEXT,
  user_agent TEXT,
  criado_em TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- PARTE 2: CADASTROS FISCAIS E ESTRUTURAS DE EMPRESA
-- ==============================================================================

CREATE TABLE IF NOT EXISTS empresas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  razao_social TEXT NOT NULL,
  nome_fantasia TEXT,
  cnpj TEXT NOT NULL,
  regime_tributario TEXT NOT NULL DEFAULT 'Simples Nacional',
  aliquota_efetiva_simples NUMERIC(10,4),
  uf TEXT,
  municipio_codigo_ibge TEXT,
  ativo BOOLEAN DEFAULT true,
  created_by UUID REFERENCES usuarios_perfil(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, cnpj)
);

CREATE TABLE IF NOT EXISTS certificados_digitais (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'A1',
  arquivo_criptografado BYTEA,
  senha_criptografada BYTEA,
  data_vencimento DATE NOT NULL,
  alerta_enviado BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clientes_fornecedores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'Cliente' CHECK (tipo IN ('Cliente', 'Fornecedor', 'Ambos')),
  cnpj_cpf TEXT,
  nome TEXT NOT NULL,
  regime_tributario TEXT,
  aliquota_efetiva_simples NUMERIC(10,4),
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS produtos_servicos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  descricao TEXT NOT NULL,
  ncm TEXT,
  cest TEXT,
  imune BOOLEAN DEFAULT false,
  isento BOOLEAN DEFAULT false,
  sujeito_imposto_seletivo BOOLEAN DEFAULT false,
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tabela_ncm (
  codigo TEXT PRIMARY KEY,
  descricao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tabela_cfop (
  codigo TEXT PRIMARY KEY,
  descricao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tabela_cst_csosn (
  codigo TEXT PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('CST', 'CSOSN')),
  descricao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS municipios_uf (
  codigo_ibge TEXT PRIMARY KEY,
  municipio TEXT NOT NULL,
  uf CHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS tabela_cest (
  codigo TEXT PRIMARY KEY,
  ncm TEXT,
  descricao TEXT NOT NULL,
  segmento TEXT
);

CREATE TABLE IF NOT EXISTS tabela_cbenef (
  codigo TEXT PRIMARY KEY,
  uf CHAR(2) NOT NULL,
  descricao TEXT NOT NULL,
  fundamento_legal TEXT
);

CREATE TABLE IF NOT EXISTS tabela_cnae (
  codigo TEXT PRIMARY KEY,
  descricao TEXT NOT NULL,
  secao TEXT
);

CREATE TABLE IF NOT EXISTS tabela_paises (
  codigo_bacen TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  sigla_iso CHAR(2)
);

CREATE TABLE IF NOT EXISTS tabela_regimes_especiais (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  descricao TEXT NOT NULL,
  uf CHAR(2),
  tributo_afetado TEXT,
  percentual_beneficio NUMERIC(6,4),
  fundamento_legal TEXT,
  vigencia_inicio DATE NOT NULL,
  vigencia_fim DATE,
  status TEXT DEFAULT 'vigente' CHECK (status IN ('vigente', 'encerrado')),
  observacao TEXT
);

-- ==============================================================================
-- PARTE 3: DOCUMENTOS, LOTES E AUDITORIA DE REFORMA / MOTOR FISCAL
-- ==============================================================================

CREATE TABLE IF NOT EXISTS lotes_em_massa (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID NOT NULL REFERENCES empresas(id),
  nome_lote TEXT,
  origem TEXT NOT NULL DEFAULT 'upload' CHECK (origem IN ('upload', 'xml_batch', 'api')),
  total_documentos INT NOT NULL DEFAULT 0,
  total_concluidos INT NOT NULL DEFAULT 0,
  total_com_erro INT NOT NULL DEFAULT 0,
  total_pendente_revisao INT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'recebido' CHECK (status IN ('recebido', 'processando', 'concluido_parcial', 'concluido', 'concluido_com_erros')),
  criado_por UUID REFERENCES usuarios_perfil(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  concluido_em TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS documentos_fiscais (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id),
  tipo_documento TEXT NOT NULL, -- 'NF-e', 'NFC-e', 'CT-e', 'MDF-e'
  chave_acesso CHAR(44),
  hash_arquivo TEXT,
  origem_captura TEXT DEFAULT 'Upload',
  arquivo_url TEXT,
  tamanho_bytes INT,
  status_sefaz TEXT DEFAULT 'Regular',
  cnpj_emitente TEXT,
  cnpj_destinatario TEXT,
  tipo_operacao TEXT CHECK (tipo_operacao IN ('entrada', 'saida', 'indefinido')),
  xml_original TEXT,
  xml_parseado_em TIMESTAMPTZ,
  xml_erro_parser TEXT,
  cte_modal TEXT,
  cte_uf_inicio CHAR(2),
  cte_uf_fim CHAR(2),
  mdfe_documentos_vinculados JSONB,
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, chave_acesso)
);

CREATE TABLE IF NOT EXISTS lotes_documentos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id),
  lote_em_massa_id UUID REFERENCES lotes_em_massa(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'Pendente',
  usuario_responsavel UUID REFERENCES usuarios_perfil(id),
  total_itens INT DEFAULT 0,
  total_divergencias INT DEFAULT 0,
  percentual_conformidade NUMERIC(5,2) DEFAULT 0,
  prompt_tokens INT DEFAULT 0,
  completion_tokens INT DEFAULT 0,
  custo_estimado NUMERIC(10,6) DEFAULT 0,
  custo_estimado_brl NUMERIC(10,2) DEFAULT 0,
  tempo_execucao_ms INT DEFAULT 0,
  logs_erro TEXT,
  processamento_iniciado_em TIMESTAMPTZ,
  modelo_ia_etapa1 TEXT,
  modelo_ia_etapa2 TEXT,
  versao_prompt TEXT,
  versao_motor_fiscal TEXT,
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS itens_nota_auditados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id UUID NOT NULL REFERENCES lotes_documentos(id) ON DELETE CASCADE,
  documento_id UUID REFERENCES documentos_fiscais(id) ON DELETE SET NULL,
  nome_produto VARCHAR(255),
  valor_item NUMERIC(14,2) DEFAULT 0,
  ncm_original TEXT,
  ncm_correto TEXT,
  cfop_original TEXT,
  cfop_correto TEXT,
  cst_original TEXT,
  cst_correto TEXT,
  csosn_original TEXT,
  csosn_correto TEXT,
  cest_original TEXT,
  cest_correto TEXT,
  cst_ibs_cbs_original TEXT,
  cst_ibs_cbs_correto TEXT,
  alerta_divergencia BOOLEAN DEFAULT false,
  justificativa_ia TEXT,
  enquadramento_reforma TEXT,
  percentual_confianca_ia NUMERIC(5,2),
  aliquota_ibs_original NUMERIC(10,4) DEFAULT 0,
  aliquota_ibs_correta NUMERIC(10,4) DEFAULT 0,
  aliquota_cbs_original NUMERIC(10,4) DEFAULT 0,
  aliquota_cbs_correta NUMERIC(10,4) DEFAULT 0,
  imposto_seletivo_aplicavel BOOLEAN DEFAULT false,
  cashback_elegivel BOOLEAN DEFAULT false,
  split_payment_obrigatorio BOOLEAN DEFAULT false,
  credito_ibs_cbs_liberado BOOLEAN DEFAULT false,
  feedback_usuario TEXT
);

CREATE TABLE IF NOT EXISTS parametros_fiscais (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ano INT NOT NULL UNIQUE,
  vigencia_inicio DATE NOT NULL,
  vigencia_fim DATE,
  aliquota_ibs_padrao NUMERIC(10,4) NOT NULL,
  aliquota_cbs_padrao NUMERIC(10,4) NOT NULL,
  aliquota_ibs_reduzida_60 NUMERIC(10,4) NOT NULL,
  aliquota_cbs_reduzida_60 NUMERIC(10,4) NOT NULL,
  aliquota_ibs_reduzida_100 NUMERIC(10,4) DEFAULT 0.0,
  aliquota_cbs_reduzida_100 NUMERIC(10,4) DEFAULT 0.0,
  provisorio BOOLEAN DEFAULT false,
  observacao TEXT
);

CREATE TABLE IF NOT EXISTS cache_auditoria_produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hash_produto TEXT NOT NULL UNIQUE,
  nome_produto TEXT,
  ncm_correto TEXT,
  cfop_correto TEXT,
  cst_correto TEXT,
  csosn_correto TEXT,
  cest_correto TEXT,
  cst_ibs_cbs_correto TEXT,
  enquadramento_reforma TEXT,
  percentual_confianca_ia NUMERIC(5,2),
  aliquota_ibs_correta NUMERIC(10,4),
  aliquota_cbs_correta NUMERIC(10,4),
  imposto_seletivo_aplicavel BOOLEAN,
  cashback_elegivel BOOLEAN,
  split_payment_obrigatorio BOOLEAN,
  justificativa_ia TEXT,
  versao_motor TEXT DEFAULT 'V8.0',
  ano_parametro_fiscal INT,
  hit_count INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS telemetria_auditoria_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  usuario_id UUID REFERENCES usuarios_perfil(id),
  lote_id UUID REFERENCES lotes_documentos(id) ON DELETE CASCADE,
  tempo_total_ms INT,
  tempo_ia_ms INT,
  tempo_banco_ms INT,
  tokens_utilizados INT,
  custo_usd NUMERIC(10,6),
  status_final TEXT,
  detalhe_erro TEXT,
  stack_trace TEXT,
  criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS logs_api_externa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  lote_id UUID REFERENCES lotes_documentos(id) ON DELETE CASCADE,
  provedor TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  status_http INT,
  tempo_resposta_ms INT,
  tokens_prompt INT,
  tokens_completion INT,
  custo_usd NUMERIC(10,6),
  erro TEXT,
  criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agenda_fiscal (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id),
  titulo TEXT NOT NULL,
  descricao TEXT,
  tipo_obrigacao TEXT,
  data_vencimento DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'A Fazer',
  responsavel_id UUID REFERENCES usuarios_perfil(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_mensagens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id),
  remetente_id UUID REFERENCES usuarios_perfil(id),
  mensagem TEXT NOT NULL,
  lida BOOLEAN DEFAULT false,
  criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exportacoes_obrigacoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID REFERENCES empresas(id),
  tipo TEXT NOT NULL,
  periodo_referencia TEXT NOT NULL,
  arquivo_url TEXT,
  status TEXT DEFAULT 'Gerado',
  criado_em TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- PARTE 4: TABELAS E MOTORES ESPECÍFICOS DE REGIMES TRIBUTÁRIOS (BLOCOS 1 AO 45)
-- ==============================================================================

-- --- BLOCCOS SIMPLES NACIONAL (Anexos I-V e Fator R) ---
CREATE TABLE IF NOT EXISTS simples_nacional_faixas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  anexo TEXT NOT NULL CHECK (anexo IN ('I', 'II', 'III', 'IV', 'V')),
  faixa INT NOT NULL CHECK (faixa BETWEEN 1 AND 6),
  receita_bruta_ate NUMERIC(15,2) NOT NULL,
  aliquota_nominal NUMERIC(6,4) NOT NULL,
  valor_deduzir NUMERIC(15,2) NOT NULL DEFAULT 0,
  vigencia_inicio DATE NOT NULL DEFAULT '2024-01-01',
  vigencia_fim DATE,
  fundamento_legal TEXT DEFAULT 'LC 123/2006, art. 18, Anexos I a V',
  status TEXT NOT NULL DEFAULT 'vigente' CHECK (status IN ('vigente', 'encerrado', 'revogado')),
  versao INT NOT NULL DEFAULT 1,
  observacao TEXT,
  legislacao_id UUID,
  elaborado_por UUID REFERENCES usuarios_perfil(id),
  revisado_por UUID REFERENCES usuarios_perfil(id),
  aprovado_por UUID REFERENCES usuarios_perfil(id),
  data_revisao TIMESTAMPTZ,
  data_aprovacao TIMESTAMPTZ,
  status_regira TEXT NOT NULL DEFAULT 'aprovado' CHECK (status_regira IN ('rascunho', 'em_revisao', 'aprovado', 'rejeitado')),
  UNIQUE (anexo, faixa, vigencia_inicio)
);

CREATE TABLE IF NOT EXISTS simples_nacional_memoria_calculo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  data_calculo TIMESTAMPTZ DEFAULT now(),
  anexo_utilizado TEXT NOT NULL,
  faixa_utilizada INT NOT NULL,
  faixa_id UUID REFERENCES simples_nacional_faixas(id),
  receita_bruta_12m NUMERIC(15,2) NOT NULL,
  aliquota_nominal NUMERIC(6,4) NOT NULL,
  valor_deduzir NUMERIC(15,2) NOT NULL,
  aliquota_efetiva NUMERIC(8,6) NOT NULL,
  valor_nota NUMERIC(15,2) NOT NULL,
  valor_devido NUMERIC(15,2) NOT NULL,
  fator_r NUMERIC(8,6),
  anexo_original_informado TEXT,
  anexo_foi_alterado_por_fator_r BOOLEAN DEFAULT false,
  usuario_id UUID REFERENCES usuarios_perfil(id),
  versao_faixa_utilizada INT,
  observacao TEXT,
  hash_integridade TEXT,
  status_revisao TEXT NOT NULL DEFAULT 'aprovado' CHECK (status_revisao IN ('aprovado', 'pendente_revisao', 'rejeitado')),
  motivo_revisao TEXT,
  cfop_utilizado TEXT,
  cfop_desconhecido BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS configuracao_cfop_tributavel (
  cfop TEXT PRIMARY KEY,
  descricao TEXT NOT NULL,
  tributa_simples BOOLEAN NOT NULL DEFAULT true,
  tributa_icms BOOLEAN NOT NULL DEFAULT true,
  tipo_operacao TEXT NOT NULL CHECK (tipo_operacao IN ('venda', 'devolucao', 'remessa', 'retorno_remessa', 'industrializacao', 'consignacao', 'demonstracao', 'bonificacao', 'brinde', 'exportacao', 'importacao', 'transferencia', 'outro')),
  observacao TEXT
);

-- --- BLOCOS MEI ---
CREATE TABLE IF NOT EXISTS mei_parametros_anuais (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ano INT NOT NULL UNIQUE,
  limite_faturamento_anual NUMERIC(15,2) NOT NULL DEFAULT 81000.00,
  limite_faturamento_caminhoneiro NUMERIC(15,2) NOT NULL DEFAULT 251600.00,
  percentual_tolerancia_excesso NUMERIC(5,4) NOT NULL DEFAULT 0.20,
  das_inss NUMERIC(10,2) NOT NULL,
  das_icms NUMERIC(10,2) NOT NULL DEFAULT 1.00,
  das_iss NUMERIC(10,2) NOT NULL DEFAULT 5.00,
  fundamento_legal TEXT DEFAULT 'LC 123/2006, art. 18-A (SIMEI)',
  legislacao_id UUID,
  vigencia_inicio DATE NOT NULL,
  vigencia_fim DATE,
  status TEXT NOT NULL DEFAULT 'vigente' CHECK (status IN ('vigente', 'encerrado', 'revogado')),
  observacao TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mei_memoria_calculo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  data_calculo TIMESTAMPTZ DEFAULT now(),
  competencia DATE NOT NULL,
  tipo_atividade TEXT NOT NULL CHECK (tipo_atividade IN ('comercio_industria', 'servico', 'comercio_e_servico')),
  das_devido NUMERIC(10,2) NOT NULL,
  receita_mes NUMERIC(15,2) NOT NULL,
  receita_acumulada_ano NUMERIC(15,2) NOT NULL,
  limite_proporcional NUMERIC(15,2) NOT NULL,
  percentual_do_limite_usado NUMERIC(6,4),
  situacao TEXT NOT NULL CHECK (situacao IN ('dentro_limite', 'excesso_ate_20', 'excesso_acima_20')),
  status_revisao TEXT NOT NULL DEFAULT 'aprovado' CHECK (status_revisao IN ('aprovado', 'pendente_revisao', 'rejeitado')),
  motivo_revisao TEXT,
  usuario_id UUID REFERENCES usuarios_perfil(id),
  hash_integridade TEXT,
  observacao TEXT
);

-- --- BLOCOS LUCRO PRESUMIDO ---
CREATE TABLE IF NOT EXISTS presumido_parametros (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ano INT NOT NULL,
  tipo_atividade TEXT NOT NULL CHECK (tipo_atividade IN ('comercio', 'industria', 'servico_geral', 'servico_transporte_carga', 'servico_transporte_passageiro', 'servico_hospitalar', 'revenda_combustivel')),
  presuncao_irpj NUMERIC(6,4) NOT NULL,
  presuncao_csll NUMERIC(6,4) NOT NULL,
  aliquota_irpj NUMERIC(6,4) NOT NULL DEFAULT 0.15,
  aliquota_adicional_irpj NUMERIC(6,4) NOT NULL DEFAULT 0.10,
  limite_mensal_adicional NUMERIC(15,2) NOT NULL DEFAULT 20000.00,
  aliquota_csll NUMERIC(6,4) NOT NULL DEFAULT 0.09,
  aliquota_pis NUMERIC(6,4) NOT NULL DEFAULT 0.0065,
  aliquota_cofins NUMERIC(6,4) NOT NULL DEFAULT 0.03,
  vigencia_inicio DATE NOT NULL,
  vigencia_fim DATE,
  status TEXT NOT NULL DEFAULT 'vigente' CHECK (status IN ('vigente', 'encerrado', 'revogado')),
  fundamento_legal TEXT DEFAULT 'Lei 9.249/1995, arts. 15 e 20',
  observacao TEXT,
  UNIQUE (ano, tipo_atividade, vigencia_inicio)
);

CREATE TABLE IF NOT EXISTS presumido_memoria_calculo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  data_calculo TIMESTAMPTZ DEFAULT now(),
  competencia DATE NOT NULL,
  tipo_atividade TEXT NOT NULL,
  receita_bruta_mes NUMERIC(15,2) NOT NULL,
  base_presumida_irpj NUMERIC(15,2),
  irpj_valor NUMERIC(15,2),
  irpj_adicional NUMERIC(15,2),
  base_presumida_csll NUMERIC(15,2),
  csll_valor NUMERIC(15,2),
  pis_valor NUMERIC(15,2),
  cofins_valor NUMERIC(15,2),
  uf_origem CHAR(2), uf_destino CHAR(2),
  aliquota_icms_aplicada NUMERIC(5,2),
  icms_valor NUMERIC(15,2),
  municipio_iss TEXT,
  aliquota_iss_aplicada NUMERIC(5,2),
  iss_valor NUMERIC(15,2),
  total_federal NUMERIC(15,2),
  total_geral NUMERIC(15,2),
  status_revisao TEXT NOT NULL DEFAULT 'aprovado' CHECK (status_revisao IN ('aprovado', 'pendente_revisao', 'rejeitado')),
  motivo_revisao TEXT,
  usuario_id UUID REFERENCES usuarios_perfil(id),
  hash_integridade TEXT,
  observacao TEXT
);

-- --- BLOCOS LUCRO REAL ---
CREATE TABLE IF NOT EXISTS lucro_real_parametros (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ano INT NOT NULL,
  aliquota_irpj NUMERIC(6,4) NOT NULL DEFAULT 0.15,
  aliquota_adicional_irpj NUMERIC(6,4) NOT NULL DEFAULT 0.10,
  limite_mensal_adicional NUMERIC(15,2) NOT NULL DEFAULT 20000.00,
  aliquota_csll NUMERIC(6,4) NOT NULL DEFAULT 0.09,
  aliquota_pis_nao_cumulativo NUMERIC(6,4) NOT NULL DEFAULT 0.0165,
  aliquota_cofins_nao_cumulativo NUMERIC(6,4) NOT NULL DEFAULT 0.076,
  percentual_max_compensacao_prejuizo NUMERIC(6,4) NOT NULL DEFAULT 0.30, -- Trava dos 30%
  vigencia_inicio DATE NOT NULL,
  vigencia_fim DATE,
  status TEXT NOT NULL DEFAULT 'vigente' CHECK (status IN ('vigente', 'encerrado', 'revogado')),
  fundamento_legal TEXT DEFAULT 'Lei 9.430/1996 (IRPJ/CSLL Lucro Real)',
  observacao TEXT,
  UNIQUE (ano, vigencia_inicio)
);

CREATE TABLE IF NOT EXISTS lucro_real_memoria_calculo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  data_calculo TIMESTAMPTZ DEFAULT now(),
  periodo_inicio DATE NOT NULL,
  periodo_fim DATE NOT NULL,
  lucro_contabil_informado NUMERIC(15,2) NOT NULL,
  informado_por UUID REFERENCES usuarios_perfil(id),
  fonte_lucro_contabil TEXT DEFAULT 'Informado externamente pelo contador do escritório',
  adicoes_irpj NUMERIC(15,2) DEFAULT 0, exclusoes_irpj NUMERIC(15,2) DEFAULT 0,
  adicoes_csll NUMERIC(15,2) DEFAULT 0, exclusoes_csll NUMERIC(15,2) DEFAULT 0,
  lucro_real_ajustado_irpj NUMERIC(15,2),
  lucro_real_ajustado_csll NUMERIC(15,2),
  prejuizo_fiscal_acumulado_anterior NUMERIC(15,2) DEFAULT 0,
  prejuizo_compensado NUMERIC(15,2) DEFAULT 0,
  prejuizo_fiscal_remanescente NUMERIC(15,2) DEFAULT 0,
  base_irpj NUMERIC(15,2), irpj_valor NUMERIC(15,2), irpj_adicional NUMERIC(15,2),
  base_csll NUMERIC(15,2), csll_valor NUMERIC(15,2),
  receita_bruta_periodo NUMERIC(15,2) NOT NULL,
  debito_pis NUMERIC(15,2), credito_pis NUMERIC(15,2), pis_a_pagar NUMERIC(15,2),
  debito_cofins NUMERIC(15,2), credito_cofins NUMERIC(15,2), cofins_a_pagar NUMERIC(15,2),
  total_geral_devido NUMERIC(15,2),
  status_revisao TEXT NOT NULL DEFAULT 'aprovado' CHECK (status_revisao IN ('aprovado', 'pendente_revisao', 'rejeitado')),
  motivo_revisao TEXT,
  usuario_id UUID REFERENCES usuarios_perfil(id),
  hash_integridade TEXT,
  observacao TEXT
);

-- --- BLOCOS DIFAL & ICMS-ST ---
CREATE TABLE IF NOT EXISTS tabela_fcp_uf (
  uf CHAR(2) PRIMARY KEY,
  aliquota_fcp_geral NUMERIC(5,2) NOT NULL DEFAULT 0,
  possui_fcp BOOLEAN NOT NULL DEFAULT false,
  observacao TEXT DEFAULT 'Percentual geral aproximado de FCP'
);

CREATE TABLE IF NOT EXISTS difal_memoria_calculo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  documento_id UUID REFERENCES documentos_fiscais(id) ON DELETE SET NULL,
  data_calculo TIMESTAMPTZ DEFAULT now(),
  uf_origem CHAR(2) NOT NULL,
  uf_destino CHAR(2) NOT NULL,
  valor_operacao NUMERIC(15,2) NOT NULL,
  aliquota_interna_destino NUMERIC(5,2) NOT NULL,
  aliquota_interestadual NUMERIC(5,2) NOT NULL,
  base_difal NUMERIC(15,2) NOT NULL,
  difal_valor NUMERIC(15,2) NOT NULL,
  fcp_aliquota NUMERIC(5,2) DEFAULT 0,
  fcp_valor NUMERIC(15,2) DEFAULT 0,
  total_a_recolher_destino NUMERIC(15,2) NOT NULL,
  status_revisao TEXT NOT NULL DEFAULT 'aprovado' CHECK (status_revisao IN ('aprovado', 'pendente_revisao', 'rejeitado')),
  motivo_revisao TEXT,
  usuario_id UUID REFERENCES usuarios_perfil(id),
  hash_integridade TEXT
);

CREATE TABLE IF NOT EXISTS tabela_mva_icms_st (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ncm TEXT,
  cest TEXT,
  descricao TEXT NOT NULL,
  uf_destino CHAR(2) NOT NULL,
  mva_percentual NUMERIC(6,4) NOT NULL,
  fundamento_legal TEXT,
  vigencia_inicio DATE NOT NULL DEFAULT '2024-01-01',
  vigencia_fim DATE,
  status TEXT NOT NULL DEFAULT 'vigente' CHECK (status IN ('vigente', 'encerrado')),
  observacao TEXT DEFAULT 'Tabela de MVA e margens de valor agregado para ST',
  CONSTRAINT uq_mva_icms_st_ncm_uf UNIQUE (ncm, uf_destino)
);

CREATE TABLE IF NOT EXISTS icms_st_memoria_calculo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE,
  documento_id UUID REFERENCES documentos_fiscais(id) ON DELETE SET NULL,
  data_calculo TIMESTAMPTZ DEFAULT now(),
  ncm TEXT, cest TEXT,
  uf_destino CHAR(2) NOT NULL,
  valor_produto NUMERIC(15,2) NOT NULL,
  ipi_valor NUMERIC(15,2) DEFAULT 0,
  frete_valor NUMERIC(15,2) DEFAULT 0,
  outras_despesas NUMERIC(15,2) DEFAULT 0,
  mva_percentual NUMERIC(6,4),
  base_st NUMERIC(15,2),
  aliquota_interna_destino NUMERIC(5,2),
  icms_st_bruto NUMERIC(15,2),
  icms_proprio_debito NUMERIC(15,2),
  icms_st_a_recolher NUMERIC(15,2),
  status_revisao TEXT NOT NULL DEFAULT 'aprovado' CHECK (status_revisao IN ('aprovado', 'pendente_revisao', 'rejeitado')),
  motivo_revisao TEXT,
  usuario_id UUID REFERENCES usuarios_perfil(id),
  hash_integridade TEXT
);

-- --- BLOCOS CADASTROS COMPLEMENTARES E LEGISLAÇÃO ---
CREATE TABLE IF NOT EXISTS legislacao_fiscal (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tipo_norma TEXT NOT NULL CHECK (tipo_norma IN ('Lei', 'Lei Complementar', 'Emenda Constitucional', 'Decreto', 'Convênio', 'Ajuste SINIEF', 'Ato COTEPE', 'Instrução Normativa', 'Resolução', 'Portaria', 'Outro')),
  numero TEXT NOT NULL,
  ano INT NOT NULL,
  descricao TEXT NOT NULL,
  orgao_emissor TEXT,
  data_publicacao DATE,
  vigencia_inicio DATE,
  vigencia_fim DATE,
  status TEXT NOT NULL DEFAULT 'vigente' CHECK (status IN ('vigente', 'revogado', 'em_analise')),
  url_norma TEXT,
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(tipo_norma, numero, ano)
);

CREATE TABLE IF NOT EXISTS produtos_imunes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ncm TEXT NOT NULL UNIQUE,
  descricao TEXT NOT NULL,
  tipo_imunidade TEXT NOT NULL,
  base_legal TEXT DEFAULT 'Art. 150, VI, d, CF',
  ativo BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS operacoes_isentas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cfop TEXT NOT NULL UNIQUE,
  descricao TEXT NOT NULL,
  tipo_isencao TEXT NOT NULL,
  base_legal TEXT,
  ativo BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS apuracao_impostos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  competencia DATE NOT NULL,
  regime_tributario TEXT NOT NULL,
  pis_debito NUMERIC(15,2) DEFAULT 0,
  pis_credito NUMERIC(15,2) DEFAULT 0,
  pis_a_pagar NUMERIC(15,2) DEFAULT 0,
  cofins_debito NUMERIC(15,2) DEFAULT 0,
  cofins_credito NUMERIC(15,2) DEFAULT 0,
  cofins_a_pagar NUMERIC(15,2) DEFAULT 0,
  ipi_debito NUMERIC(15,2) DEFAULT 0,
  ipi_credito NUMERIC(15,2) DEFAULT 0,
  ipi_a_pagar NUMERIC(15,2) DEFAULT 0,
  irpj_valor NUMERIC(15,2) DEFAULT 0,
  csll_valor NUMERIC(15,2) DEFAULT 0,
  icms_debito NUMERIC(15,2) DEFAULT 0,
  icms_credito NUMERIC(15,2) DEFAULT 0,
  icms_a_pagar NUMERIC(15,2) DEFAULT 0,
  icms_st_valor NUMERIC(15,2) DEFAULT 0,
  difal_valor NUMERIC(15,2) DEFAULT 0,
  iss_debito NUMERIC(15,2) DEFAULT 0,
  iss_credito NUMERIC(15,2) DEFAULT 0,
  iss_a_pagar NUMERIC(15,2) DEFAULT 0,
  simples_valor NUMERIC(15,2) DEFAULT 0,
  simples_anexo TEXT,
  ibs_debito NUMERIC(15,2) DEFAULT 0,
  ibs_credito NUMERIC(15,2) DEFAULT 0,
  cbs_debito NUMERIC(15,2) DEFAULT 0,
  cbs_credito NUMERIC(15,2) DEFAULT 0,
  imposto_seletivo NUMERIC(15,2) DEFAULT 0,
  total_impostos NUMERIC(15,2) DEFAULT 0,
  total_creditos NUMERIC(15,2) DEFAULT 0,
  saldo_a_pagar NUMERIC(15,2) DEFAULT 0,
  status TEXT DEFAULT 'em_apuracao',
  fechado_em TIMESTAMPTZ,
  transmitido_em TIMESTAMPTZ,
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(empresa_id, competencia)
);

CREATE TABLE IF NOT EXISTS aliquotas_customizadas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  imposto TEXT NOT NULL,
  uf_origem CHAR(2),
  uf_destino CHAR(2),
  aliquota NUMERIC(6,4) NOT NULL,
  base_calculo TEXT,
  vigencia_inicio DATE NOT NULL,
  vigencia_fim DATE,
  ativo BOOLEAN DEFAULT true,
  UNIQUE(empresa_id, imposto, uf_origem, uf_destino, vigencia_inicio)
);

-- --- WEBHOOK STAGING E NOTIFICAÇÕES (BLOCO 24 & 44) ---
CREATE TABLE IF NOT EXISTS notas_recebimento_externo (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  empresa_id UUID NOT NULL REFERENCES empresas(id),
  origem_provedor TEXT NOT NULL,
  tipo_documento TEXT,
  chave_acesso TEXT,
  xml_bruto TEXT,
  payload_original JSONB,
  status_processamento TEXT NOT NULL DEFAULT 'pendente' CHECK (status_processamento IN ('pendente', 'processando', 'processado', 'erro', 'duplicado')),
  documento_id UUID REFERENCES documentos_fiscais(id),
  erro_processamento TEXT,
  recebido_em TIMESTAMPTZ DEFAULT now(),
  processado_em TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS alertas_legislacao (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tipo_norma TEXT NOT NULL,
  numero TEXT NOT NULL,
  ano INT NOT NULL,
  data_publicacao DATE NOT NULL,
  data_inicio_vigencia DATE,
  resumo TEXT,
  impacto TEXT,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'avaliado', 'aplicado', 'descartado'))
);

CREATE TABLE IF NOT EXISTS cache_calculo_tributario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hash_calculo TEXT NOT NULL UNIQUE,
  regime TEXT NOT NULL,
  parametros JSONB NOT NULL,
  resultado JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ DEFAULT (now() + interval '1 hour')
);

CREATE TABLE IF NOT EXISTS notificacoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE CASCADE,
  usuario_id UUID REFERENCES usuarios_perfil(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (tipo IN ('certificado_vencendo', 'obrigacao_vencendo', 'falha_processamento', 'mudanca_legislacao', 'sistema')),
  titulo TEXT NOT NULL,
  mensagem TEXT,
  referencia_tabela TEXT,
  referencia_id TEXT,
  lida BOOLEAN DEFAULT false,
  criado_em TIMESTAMPTZ DEFAULT now(),
  lida_em TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS guias_recolhimento (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  tipo_guia TEXT NOT NULL CHECK (tipo_guia IN ('DAS_SIMPLES', 'DAS_MEI', 'DARF_IRPJ', 'DARF_CSLL', 'DARF_PIS', 'DARF_COFINS')),
  codigo_receita TEXT,
  competencia_inicio DATE NOT NULL,
  competencia_fim DATE NOT NULL,
  valor NUMERIC(15,2) NOT NULL,
  data_vencimento DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'gerada' CHECK (status IN ('gerada', 'paga', 'vencida', 'cancelada')),
  origem_memoria_id BIGINT,
  origem_memoria_tabela TEXT,
  observacao TEXT DEFAULT 'Guia gerada de recolhimento tributário',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- PARTE 5: INDICES DE DESEMPENHO E COBERTURA DE BANCO DE DADOS
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_usuarios_perfil_tenant ON usuarios_perfil(tenant_id);
CREATE INDEX IF NOT EXISTS idx_empresas_cnpj ON empresas(cnpj);
CREATE INDEX IF NOT EXISTS idx_auditoria_tenant_data ON auditoria_alteracoes(tenant_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_clientes_empresa ON clientes_fornecedores(empresa_id) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_produtos_empresa ON produtos_servicos(empresa_id) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_docs_fiscais_perf_audit ON documentos_fiscais(tenant_id, created_at DESC) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_lotes_perf_audit ON lotes_documentos(tenant_id, created_at DESC) WHERE (is_deleted = false);
CREATE INDEX IF NOT EXISTS idx_lotes_empresa_data ON lotes_documentos(empresa_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_itens_lote ON itens_nota_auditados(lote_id);
CREATE INDEX IF NOT EXISTS idx_itens_alerta ON itens_nota_auditados(alerta_divergencia) WHERE (alerta_divergencia = true);
CREATE INDEX IF NOT EXISTS idx_cache_hash ON cache_auditoria_produtos(hash_produto);
CREATE INDEX IF NOT EXISTS idx_telemetria_lote ON telemetria_auditoria_logs(lote_id);
CREATE INDEX IF NOT EXISTS idx_lotes_travados ON lotes_documentos(status, processamento_iniciado_em) WHERE (status = 'Processando');
CREATE INDEX IF NOT EXISTS idx_icms_uf_vigente ON tabela_icms_uf(uf, vigencia_inicio DESC) WHERE (status = 'vigente');
CREATE INDEX IF NOT EXISTS idx_simples_faixas_vigente ON simples_nacional_faixas(anexo, faixa, vigencia_inicio DESC) WHERE (status = 'vigente');
CREATE INDEX IF NOT EXISTS idx_memoria_calculo_empresa ON simples_nacional_memoria_calculo(empresa_id, data_calculo DESC);
CREATE INDEX IF NOT EXISTS idx_legislacao_status ON legislacao_fiscal(status) WHERE (status = 'vigente');
CREATE INDEX IF NOT EXISTS idx_mei_memoria_empresa ON mei_memoria_calculo(empresa_id, competencia DESC);
CREATE INDEX IF NOT EXISTS idx_presumido_memoria_empresa ON presumido_memoria_calculo(empresa_id, competencia DESC);
CREATE INDEX IF NOT EXISTS idx_lucro_real_memoria_empresa ON lucro_real_memoria_calculo(empresa_id, periodo_inicio DESC);
CREATE INDEX IF NOT EXISTS idx_difal_memoria_empresa ON difal_memoria_calculo(empresa_id, data_calculo DESC);
CREATE INDEX IF NOT EXISTS idx_mva_ncm_uf ON tabela_mva_icms_st(ncm, uf_destino) WHERE (status = 'vigente');
CREATE INDEX IF NOT EXISTS idx_mva_cest_uf ON tabela_mva_icms_st(cest, uf_destino) WHERE (status = 'vigente');
CREATE INDEX IF NOT EXISTS idx_icms_st_memoria_empresa ON icms_st_memoria_calculo(empresa_id, data_calculo DESC);
CREATE INDEX IF NOT EXISTS idx_lotes_em_massa_tenant ON lotes_em_massa(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lotes_documentos_em_massa ON lotes_documentos(lote_em_massa_id) WHERE (lote_em_massa_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_apuracao_impostos_empresa ON apuracao_impostos(empresa_id, competencia DESC);
CREATE INDEX IF NOT EXISTS idx_aliquotas_customizadas_empresa ON aliquotas_customizadas(empresa_id);
CREATE INDEX IF NOT EXISTS idx_docs_tipo_operacao ON documentos_fiscais(empresa_id, tipo_operacao, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notas_recebimento_pendentes ON notas_recebimento_externo(tenant_id, status_processamento) WHERE (status_processamento = 'pendente');
CREATE INDEX IF NOT EXISTS idx_auditoria_tenant_registro ON auditoria_alteracoes(tenant_id, tabela_afetada, registro_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_login_usuario ON auditoria_login(usuario_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_auditoria_login_tenant ON auditoria_login(tenant_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_notificacoes_usuario_nao_lida ON notificacoes(usuario_id, criado_em DESC) WHERE (lida = false);
CREATE INDEX IF NOT EXISTS idx_notificacoes_tenant ON notificacoes(tenant_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_guias_empresa ON guias_recolhimento(empresa_id, data_vencimento DESC);
CREATE INDEX IF NOT EXISTS idx_cache_calculo_hash ON cache_calculo_tributario(hash_calculo);
CREATE INDEX IF NOT EXISTS idx_cache_calculo_expires ON cache_calculo_tributario(expires_at);

-- ==============================================================================
-- PARTE 6: CONFIGURAÇÕES DE LINHAS E TRIGGERS DE ATUALIZAÇÃO AUTOMÁTICA
-- ==============================================================================

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  new.updated_at := now();
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trg_cache_updated_at ON cache_auditoria_produtos;
CREATE TRIGGER trg_cache_updated_at
  BEFORE UPDATE ON cache_auditoria_produtos
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ==============================================================================
-- PARTE 7: SEGURANÇA E ISOLAMENTO MULTI-TENANT (RLS)
-- ==============================================================================

CREATE OR REPLACE FUNCTION auth_tenant_id() RETURNS UUID
LANGUAGE sql SECURITY DEFINER STABLE
SET search_path = public AS $$
  SELECT tenant_id FROM usuarios_perfil WHERE id = auth.uid();
$$;

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios_perfil ENABLE ROW LEVEL SECURITY;
ALTER TABLE convites_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificados_digitais ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes_fornecedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos_servicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE documentos_fiscais ENABLE ROW LEVEL SECURITY;
ALTER TABLE lotes_documentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE itens_nota_auditados ENABLE ROW LEVEL SECURITY;
ALTER TABLE cache_auditoria_produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetria_auditoria_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_api_externa ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_fiscal ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_mensagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE exportacoes_obrigacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE lgpd_consentimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE simples_nacional_memoria_calculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE mei_memoria_calculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE presumido_memoria_calculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE lucro_real_memoria_calculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE difal_memoria_calculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE icms_st_memoria_calculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE apuracao_impostos ENABLE ROW LEVEL SECURITY;
ALTER TABLE aliquotas_customizadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE notas_recebimento_externo ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE guias_recolhimento ENABLE ROW LEVEL SECURITY;
ALTER TABLE simples_nacional_faixas ENABLE ROW LEVEL SECURITY;
ALTER TABLE mei_parametros_anuais ENABLE ROW LEVEL SECURITY;
ALTER TABLE presumido_parametros ENABLE ROW LEVEL SECURITY;
ALTER TABLE lucro_real_parametros ENABLE ROW LEVEL SECURITY;
ALTER TABLE parametros_fiscais ENABLE ROW LEVEL SECURITY;

-- POLICIES DE EXCLUSIVIDADE POR TENANT (EXEMPLOS CHAVE)
CREATE POLICY ts_tenants ON tenants FOR ALL USING (id = auth_tenant_id());
CREATE POLICY ts_perfis ON usuarios_perfil FOR ALL USING (tenant_id = auth_tenant_id() OR id = auth.uid());
CREATE POLICY ts_empresas ON empresas FOR ALL USING (tenant_id = auth_tenant_id());
CREATE POLICY ts_docs ON documentos_fiscais FOR ALL USING (tenant_id = auth_tenant_id());
CREATE POLICY ts_lotes ON lotes_documentos FOR ALL USING (tenant_id = auth_tenant_id());
CREATE POLICY ts_guias ON guias_recolhimento FOR ALL USING (empresa_id IN (SELECT id FROM empresas WHERE tenant_id = auth_tenant_id()));

-- ==============================================================================
-- PARTE 8: TRIGGERS COMPLEXAS DE AUDITORIA UNIFICADA DE LOGS (BLOCO 25 & 40)
-- ==============================================================================

CREATE OR REPLACE FUNCTION fn_auditoria_alteracoes()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public AS $$
DECLARE
  v_usuario_id UUID;
  v_tenant_id UUID;
  v_registro_id TEXT;
  v_dados_antes JSONB;
  v_dados_depois JSONB;
BEGIN
  BEGIN
    v_usuario_id := auth.uid();
  EXCEPTION WHEN OTHERS THEN
    v_usuario_id := NULL;
  END;

  IF TG_OP = 'INSERT' THEN
    v_tenant_id := new.tenant_id;
    v_registro_id := new.id::text;
    v_dados_antes := NULL;
    v_dados_depois := to_jsonb(new);
  ELSIF TG_OP = 'UPDATE' THEN
    v_tenant_id := new.tenant_id;
    v_registro_id := new.id::text;
    v_dados_antes := to_jsonb(old);
    v_dados_depois := to_jsonb(new);
  ELSIF TG_OP = 'DELETE' THEN
    v_tenant_id := old.tenant_id;
    v_registro_id := old.id::text;
    v_dados_antes := to_jsonb(old);
    v_dados_depois := NULL;
  END IF;

  INSERT INTO auditoria_alteracoes (tenant_id, usuario_id, tabela_afetada, registro_id, dados_antes, dados_depois, operacao)
  VALUES (v_tenant_id, v_usuario_id, TG_TABLE_NAME, v_registro_id, v_dados_antes, v_dados_depois, TG_OP);

  IF TG_OP = 'DELETE' THEN
    RETURN old;
  ELSE
    RETURN new;
  END IF;
END;
$$;

-- ==============================================================================
-- PARTE 9: PROCEDIMENTOS DO MOTOR TRIBUTÁRIO MATEMÁTICO SÊNIOR (BLOCOS 1-45)
-- ==============================================================================

-- [BLOCO 3] Fator R (Cálculo Folha / Faturamento)
CREATE OR REPLACE FUNCTION fn_calcular_fator_r(
  p_folha_pagamento_12m NUMERIC,
  p_receita_bruta_12m NUMERIC
) RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  v_fator_r NUMERIC(8,6);
  v_anexo_recomendado TEXT;
BEGIN
  IF p_receita_bruta_12m IS NULL OR p_receita_bruta_12m <= 0 THEN
    RETURN jsonb_build_object('erro', 'Receita bruta acumulada (RBT12) inválida.');
  END IF;
  IF p_folha_pagamento_12m IS NULL OR p_folha_pagamento_12m < 0 THEN
    RETURN jsonb_build_object('erro', 'Folha de pagamento inválida.');
  END IF;

  v_fator_r := p_folha_pagamento_12m / p_receita_bruta_12m;
  v_anexo_recomendado := CASE WHEN v_fator_r >= 0.28 THEN 'III' ELSE 'V' END;

  RETURN jsonb_build_object(
    'folha_pagamento_12m', p_folha_pagamento_12m,
    'receita_bruta_12m', p_receita_bruta_12m,
    'fator_r', round(v_fator_r, 6),
    'fator_r_pct', round(v_fator_r * 100, 4),
    'anexo_recomendado', v_anexo_recomendado,
    'regra_aplicada', 'Fator R >= 28% -> Anexo III; Fator R < 28% -> Anexo V (LC 123/2006, art. 18, §5º-J)'
  );
END;
$$;

-- [BLOCO 4] SHA-256 integridade de logs
CREATE OR REPLACE FUNCTION fn_gerar_hash_memoria_calculo()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
DECLARE
  v_texto_base TEXT;
BEGIN
  v_texto_base := concat_ws('|',
    new.empresa_id::text,
    new.anexo_utilizado,
    new.faixa_utilizada::text,
    new.receita_bruta_12m::text,
    new.aliquota_nominal::text,
    new.valor_deduzir::text,
    new.aliquota_efetiva::text,
    new.valor_nota::text,
    new.valor_devido::text,
    coalesce(new.fator_r::text, ''),
    new.data_calculo::text
  );
  new.hash_integridade := encode(digest(v_texto_base, 'sha256'), 'hex');
  RETURN new;
END;
$$;

-- [BLOCO 2] Simples Nacional Core Engine com Mediana de Validação
CREATE OR REPLACE FUNCTION fn_calcular_simples_nacional(
  p_anexo TEXT,
  p_receita_bruta_12m NUMERIC,
  p_valor_nota NUMERIC,
  p_empresa_id UUID DEFAULT null,
  p_folha_pagamento_12m NUMERIC DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true,
  p_cfop TEXT DEFAULT null
) RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  v_faixa RECORD;
  v_aliquota_efetiva NUMERIC(8,6);
  v_valor_simples NUMERIC(15,2);
  v_anexo_original TEXT := p_anexo;
  v_anexo_final TEXT := p_anexo;
  v_fator_r_resultado JSONB;
  v_fator_r_valor NUMERIC(8,6);
  v_anexo_alterado BOOLEAN := false;
  v_e_devolucao BOOLEAN := false;
  v_cfop_tributavel BOOLEAN := true;
  v_cfop_desconhecido BOOLEAN := false;
  v_status_revisao TEXT := 'aprovado';
  v_motivo_revisao TEXT;
BEGIN
  -- Validações básicas de entrada
  IF p_anexo NOT IN ('I', 'II', 'III', 'IV', 'V') THEN
    RETURN jsonb_build_object('erro', format('Anexo "%s" inválido.', p_anexo));
  END IF;
  IF p_valor_nota IS NULL OR p_valor_nota = 0 THEN
    RETURN jsonb_build_object('erro', 'Valor da nota não pode ser zero.');
  END IF;
  IF p_receita_bruta_12m IS NULL OR p_receita_bruta_12m <= 0 THEN
    RETURN jsonb_build_object('erro', 'Receita bruta acumulada inválida.');
  END IF;

  IF p_valor_nota < 0 THEN
    v_e_devolucao := true;
  END IF;

  -- Validação de CFOP
  IF p_cfop IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM configuracao_cfop_tributavel WHERE cfop = p_cfop) THEN
      v_cfop_desconhecido := true;
      v_status_revisao := 'pendente_revisao';
      v_motivo_revisao := format('CFOP %s não cadastrado no motor.', p_cfop);
    ELSE
      SELECT tributa_simples INTO v_cfop_tributavel FROM configuracao_cfop_tributavel WHERE cfop = p_cfop;
    END IF;
  END IF;

  IF NOT v_cfop_tributavel THEN
    RETURN jsonb_build_object(
      'tributavel', false,
      'cfop', p_cfop,
      'motivo', 'CFOP isento/devolução sem nova tributação simples.'
    );
  END IF;

  -- Fator R
  IF p_folha_pagamento_12m IS NOT NULL AND p_anexo IN ('III', 'V') THEN
    v_fator_r_resultado := fn_calcular_fator_r(p_folha_pagamento_12m, p_receita_bruta_12m);
    IF v_fator_r_resultado ? 'erro' THEN
      RETURN v_fator_r_resultado;
    END IF;
    v_anexo_final := v_fator_r_resultado ->> 'anexo_recomendado';
    v_fator_r_valor := (v_fator_r_resultado ->> 'fator_r')::numeric;
    v_anexo_alterado := (v_anexo_final <> v_anexo_original);
  END IF;

  -- Localização da Faixa
  SELECT * INTO v_faixa FROM simples_nacional_faixas 
  WHERE anexo = v_anexo_final AND status = 'vigente' AND receita_bruta_ate >= p_receita_bruta_12m
  ORDER BY faixa ASC LIMIT 1;

  IF v_faixa IS NULL THEN
    -- Acima do teto, pega a última faixa
    SELECT * INTO v_faixa FROM simples_nacional_faixas 
    WHERE anexo = v_anexo_final AND status = 'vigente'
    ORDER BY faixa DESC LIMIT 1;
  END IF;

  -- Fórmula de alíquota efetiva
  v_aliquota_efetiva := ((p_receita_bruta_12m * v_faixa.aliquota_nominal) - v_faixa.valor_deduzir) / p_receita_bruta_12m;
  IF v_aliquota_efetiva < 0 THEN
    v_aliquota_efetiva := 0;
  END IF;

  v_valor_simples := p_valor_nota * v_aliquota_efetiva;

  -- Memória e gravação
  IF p_gravar_memoria AND p_empresa_id IS NOT NULL THEN
    INSERT INTO simples_nacional_memoria_calculo (
      empresa_id, anexo_utilizado, faixa_utilizada, faixa_id, receita_bruta_12m,
      aliquota_nominal, valor_deduzir, aliquota_efetiva, valor_nota, valor_devido,
      fator_r, anexo_original_informado, anexo_foi_alterado_por_fator_r, usuario_id,
      versao_faixa_utilizada, status_revisao, motivo_revisao, cfop_utilizado, cfop_desconhecido
    ) VALUES (
      p_empresa_id, v_anexo_final, v_faixa.faixa, v_faixa.id, p_receita_bruta_12m,
      v_faixa.aliquota_nominal, v_faixa.valor_deduzir, v_aliquota_efetiva, p_valor_nota, v_valor_simples,
      v_fator_r_valor, v_anexo_original, v_anexo_alterado, p_usuario_id,
      v_faixa.versao, v_status_revisao, v_motivo_revisao, p_cfop, v_cfop_desconhecido
    );
  END IF;

  RETURN jsonb_build_object(
    'anexo_original_informado', v_anexo_original,
    'anexo_utilizado', v_anexo_final,
    'anexo_alterado_por_fator_r', v_anexo_alterado,
    'fator_r', v_fator_r_valor,
    'faixa', v_faixa.faixa,
    'receita_bruta_12m', p_receita_bruta_12m,
    'aliquota_nominal', v_faixa.aliquota_nominal,
    'aliquota_nominal_pct', round(v_faixa.aliquota_nominal * 100, 4),
    'valor_deduzir', v_faixa.valor_deduzir,
    'aliquota_efetiva', round(v_aliquota_efetiva, 6),
    'aliquota_efetiva_pct', round(v_aliquota_efetiva * 100, 4),
    'valor_nota', p_valor_nota,
    'valor_simples_devido', round(v_valor_simples, 2),
    'devolucao', v_e_devolucao,
    'status_revisao', v_status_revisao,
    'motivo_revisao', v_motivo_revisao,
    'fundamento_legal', v_faixa.fundamento_legal
  );
END;
$$;

-- [BLOCO 6] MEI Engine
CREATE OR REPLACE FUNCTION fn_calcular_mei(
  p_empresa_id UUID,
  p_competencia DATE,
  p_tipo_atividade TEXT,
  p_receita_mes NUMERIC,
  p_data_abertura DATE,
  p_receita_acumulada_ano NUMERIC,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true
) RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  v_parametros RECORD;
  v_das_devido NUMERIC(10,2);
  v_meses_ativos_no_ano INT;
  v_limite_proporcional NUMERIC(15,2);
  v_percentual_usado NUMERIC(6,4);
  v_situacao TEXT;
  v_ano INT;
  v_alerta TEXT;
BEGIN
  IF p_tipo_atividade NOT IN ('comercio_industria', 'servico', 'comercio_e_servico') THEN
    RETURN jsonb_build_object('erro', 'Tipo de atividade MEI inválida.');
  END IF;
  IF p_receita_mes IS NULL OR p_receita_mes < 0 THEN
    RETURN jsonb_build_object('erro', 'Receita do mês inválida.');
  END IF;

  v_ano := extract(year from p_competencia)::int;
  SELECT * INTO v_parametros FROM mei_parametros_anuais WHERE ano = v_ano AND status = 'vigente';

  IF v_parametros IS NULL THEN
    RETURN jsonb_build_object('erro', format('Parâmetros MEI não cadastrados para o ano %s.', v_ano));
  END IF;

  -- Composição DAS
  v_das_devido := v_parametros.das_inss;
  IF p_tipo_atividade IN ('comercio_industria', 'comercio_e_servico') THEN
    v_das_devido := v_das_devido + v_parametros.das_icms;
  END IF;
  IF p_tipo_atividade IN ('servico', 'comercio_e_servico') THEN
    v_das_devido := v_das_devido + v_parametros.das_iss;
  END IF;

  -- Limite Proporcional
  IF extract(year from p_data_abertura) = v_ano THEN
    v_meses_ativos_no_ano := 12 - extract(month from p_data_abertura)::int + 1;
  ELSE
    v_meses_ativos_no_ano := 12;
  END IF;

  v_limite_proporcional := round((v_parametros.limite_faturamento_anual / 12) * v_meses_ativos_no_ano, 2);
  v_percentual_usado := p_receita_acumulada_ano / v_limite_proporcional;

  IF p_receita_acumulada_ano <= v_limite_proporcional THEN
    v_situacao := 'dentro_limite';
  ELSIF p_receita_acumulada_ano <= v_limite_proporcional * (1 + v_parametros.percentual_tolerancia_excesso) THEN
    v_situacao := 'excesso_ate_20';
    v_alerta := 'DAS complementar sobre o excedente é devido. Planeje a migração para Microempresa.';
  ELSE
    v_situacao := 'excesso_acima_20';
    v_alerta := 'Desenquadramento retroativo obrigatório! Tributação retroativa como ME desde janeiro do ano corrente.';
  END IF;

  IF p_gravar_memoria AND p_empresa_id IS NOT NULL THEN
    INSERT INTO mei_memoria_calculo (
      empresa_id, competencia, tipo_atividade, das_devido, receita_mes, receita_acumulada_ano,
      limite_proporcional, percentual_do_limite_usado, situacao, status_revisao, motivo_revisao, usuario_id
    ) VALUES (
      p_empresa_id, p_competencia, p_tipo_atividade, v_das_devido, p_receita_mes, p_receita_acumulada_ano,
      v_limite_proporcional, v_percentual_usado, v_situacao, 
      CASE WHEN v_situacao = 'excesso_acima_20' THEN 'pendente_revisao'::text ELSE 'aprovado'::text END,
      v_alerta, p_usuario_id
    );
  END IF;

  RETURN jsonb_build_object(
    'competencia', p_competencia,
    'tipo_atividade', p_tipo_atividade,
    'das_devido', v_das_devido,
    'composicao_das', jsonb_build_object(
      'inss', v_parametros.das_inss,
      'icms', CASE WHEN p_tipo_atividade IN ('comercio_industria', 'comercio_e_servico') THEN v_parametros.das_icms ELSE 0 END,
      'iss', CASE WHEN p_tipo_atividade IN ('servico', 'comercio_e_servico') THEN v_parametros.das_iss ELSE 0 END
    ),
    'receita_mes', p_receita_mes,
    'receita_acumulada_ano', p_receita_acumulada_ano,
    'limite_proporcional', v_limite_proporcional,
    'percentual_do_limite_usado', round(v_percentual_usado * 100, 2),
    'situacao', v_situacao,
    'alerta', v_alerta,
    'fundamento_legal', v_parametros.fundamento_legal
  );
END;
$$;

-- [BLOCO 7/12] Lucro Presumido Engine
CREATE OR REPLACE FUNCTION fn_calcular_lucro_presumido(
  p_empresa_id UUID,
  p_competencia DATE,
  p_tipo_atividade TEXT,
  p_receita_bruta_mes NUMERIC,
  p_e_venda_produto BOOLEAN,
  p_uf_origem CHAR(2) DEFAULT null,
  p_uf_destino CHAR(2) DEFAULT null,
  p_aliquota_iss NUMERIC DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true
) RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  v_param RECORD;
  v_base_irpj NUMERIC(15,2);
  v_base_csll NUMERIC(15,2);
  v_irpj NUMERIC(15,2);
  v_irpj_adicional NUMERIC(15,2);
  v_csll NUMERIC(15,2);
  v_pis NUMERIC(15,2);
  v_cofins NUMERIC(15,2);
  v_icms NUMERIC(15,2) := 0;
  v_iss NUMERIC(15,2) := 0;
  v_aliquota_icms NUMERIC(5,2) := 0;
  v_total_federal NUMERIC(15,2);
  v_total_geral NUMERIC(15,2);
  v_ano INT;
  v_status_revisao TEXT := 'aprovado';
  v_motivo TEXT;
BEGIN
  IF p_receita_bruta_mes IS NULL OR p_receita_bruta_mes <= 0 THEN
    RETURN jsonb_build_object('erro', 'Receita do mês inválida.');
  END IF;

  v_ano := extract(year from p_competencia)::int;
  SELECT * INTO v_param FROM presumido_parametros 
  WHERE ano = v_ano AND tipo_atividade = p_tipo_atividade AND status = 'vigente';

  IF v_param IS NULL THEN
    RETURN jsonb_build_object('erro', format('Parâmetros de presunção não encontrados para %s (%s).', p_tipo_atividade, v_ano));
  END IF;

  -- IRPJ & CSLL
  v_base_irpj := p_receita_bruta_mes * v_param.presuncao_irpj;
  v_base_csll := p_receita_bruta_mes * v_param.presuncao_csll;

  v_irpj := v_base_irpj * v_param.aliquota_irpj;
  IF v_base_irpj > v_param.limite_mensal_adicional THEN
    v_irpj_adicional := (v_base_irpj - v_param.limite_mensal_adicional) * v_param.aliquota_adicional_irpj;
  ELSE
    v_irpj_adicional := 0;
  END IF;

  v_csll := v_base_csll * v_param.aliquota_csll;

  -- PIS & COFINS cumulativo
  v_pis := p_receita_bruta_mes * v_param.aliquota_pis;
  v_cofins := p_receita_bruta_mes * v_param.aliquota_cofins;

  v_total_federal := v_irpj + v_irpj_adicional + v_csll + v_pis + v_cofins;

  -- ICMS / ISS
  IF p_e_venda_produto THEN
    IF p_uf_origem IS NULL OR p_uf_destino IS NULL THEN
      RETURN jsonb_build_object('erro', 'UF Origem e Destino são obrigatórios para vendas físicas.');
    END IF;
    -- Alíquota interestadual simplificada para simulação
    v_aliquota_icms := CASE WHEN p_uf_origem = p_uf_destino THEN 18.0 ELSE 12.0 END;
    v_icms := p_receita_bruta_mes * (v_aliquota_icms / 100);
  ELSE
    IF p_aliquota_iss IS NULL THEN
      v_status_revisao := 'pendente_revisao';
      v_motivo := 'Alíquota de ISS municipal ausente. Verifique o cadastro local do município.';
    ELSE
      v_iss := p_receita_bruta_mes * (p_aliquota_iss / 100);
    END IF;
  END IF;

  v_total_geral := v_total_federal + v_icms + v_iss;

  IF p_gravar_memoria AND p_empresa_id IS NOT NULL THEN
    INSERT INTO presumido_memoria_calculo (
      empresa_id, competencia, tipo_atividade, receita_bruta_mes, base_presumida_irpj, irpj_valor, irpj_adicional,
      base_presumida_csll, csll_valor, pis_valor, cofins_valor, uf_origem, uf_destino, aliquota_icms_applied,
      icms_valor, municipio_iss, aliquota_iss_applied, iss_valor, total_federal, total_geral, status_revisao, motivo_revisao, usuario_id
    ) VALUES (
      p_empresa_id, p_competencia, p_tipo_atividade, p_receita_bruta_mes, v_base_irpj, v_irpj, v_irpj_adicional,
      v_base_csll, v_csll, v_pis, v_cofins, p_uf_origem, p_uf_destino, v_aliquota_icms,
      v_icms, CASE WHEN NOT p_e_venda_produto THEN 'Local' ELSE NULL END, p_aliquota_iss, v_iss, v_total_federal, v_total_geral,
      v_status_revisao, v_motivo, p_usuario_id
    );
  END IF;

  RETURN jsonb_build_object(
    'competencia', p_competencia,
    'tipo_atividade', p_tipo_atividade,
    'receita_bruta_mes', p_receita_bruta_mes,
    'irpj', jsonb_build_object(
      'base_presumida', v_base_irpj,
      'valor', round(v_irpj, 2),
      'adicional', round(v_irpj_adicional, 2)
    ),
    'csll', jsonb_build_object(
      'base_presumida', v_base_csll,
      'valor', round(v_csll, 2)
    ),
    'pis', round(v_pis, 2),
    'cofins', round(v_cofins, 2),
    'icms', CASE WHEN p_e_venda_produto THEN jsonb_build_object('aliquota_pct', v_aliquota_icms, 'valor', round(v_icms, 2)) ELSE null END,
    'iss', CASE WHEN NOT p_e_venda_produto THEN jsonb_build_object('aliquota_pct', p_aliquota_iss, 'valor', round(v_iss, 2)) ELSE null END,
    'total_federal', round(v_total_federal, 2),
    'total_geral_devido', round(v_total_geral, 2),
    'status_revisao', v_status_revisao,
    'motivo_revisao', v_motivo,
    'fundamento_legal', v_param.fundamento_legal
  );
END;
$$;

-- [BLOCO 8] Lucro Real Engine (Compensação Prejuízos 30% e Créditos não-cumulativos)
CREATE OR REPLACE FUNCTION fn_calcular_lucro_real(
  p_empresa_id UUID,
  p_periodo_inicio DATE,
  p_periodo_fim DATE,
  p_lucro_contabil_informado NUMERIC,
  p_receita_bruta_periodo NUMERIC,
  p_adicoes_irpj NUMERIC DEFAULT 0, p_exclusoes_irpj NUMERIC DEFAULT 0,
  p_adicoes_csll NUMERIC DEFAULT 0, p_exclusoes_csll NUMERIC DEFAULT 0,
  p_prejuizo_fiscal_acumulado_anterior NUMERIC DEFAULT 0,
  p_debito_pis NUMERIC DEFAULT null,
  p_credito_pis NUMERIC DEFAULT 0,
  p_debito_cofins NUMERIC DEFAULT null,
  p_credito_cofins NUMERIC DEFAULT 0,
  p_informado_por UUID DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true
) RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  v_param RECORD;
  v_meses_periodo INT;
  v_lucro_ajustado_irpj NUMERIC(15,2);
  v_lucro_ajustado_csll NUMERIC(15,2);
  v_prejuizo_compensavel NUMERIC(15,2);
  v_prejuizo_compensado NUMERIC(15,2);
  v_prejuizo_remanescente NUMERIC(15,2);
  v_base_irpj NUMERIC(15,2);
  v_irpj NUMERIC(15,2);
  v_irpj_adicional NUMERIC(15,2);
  v_base_csll NUMERIC(15,2);
  v_csll NUMERIC(15,2);
  v_limite_adicional_periodo NUMERIC(15,2);
  v_final_debito_pis NUMERIC(15,2);
  v_final_debito_cofins NUMERIC(15,2);
  v_pis_a_pagar NUMERIC(15,2);
  v_cofins_a_pagar NUMERIC(15,2);
  v_total_geral NUMERIC(15,2);
  v_ano INT;
  v_status_revisao TEXT := 'aprovado';
  v_motivo TEXT;
BEGIN
  IF p_lucro_contabil_informado IS NULL THEN
    RETURN jsonb_build_object('erro', 'Lucro contábil é obrigatório para Lucro Real.');
  END IF;
  IF p_receita_bruta_periodo IS NULL OR p_receita_bruta_periodo < 0 THEN
    RETURN jsonb_build_object('erro', 'Receita do período inválida.');
  END IF;

  v_ano := extract(year from p_periodo_inicio)::int;
  SELECT * INTO v_param FROM lucro_real_parametros WHERE ano = v_ano AND status = 'vigente';

  IF v_param IS NULL THEN
    RETURN jsonb_build_object('erro', format('Parâmetros de Lucro Real não cadastrados para o ano %s.', v_ano));
  END IF;

  -- Número de meses no faturamento (trimestral vs mensal vs anual)
  v_meses_periodo := greatest(1, (extract(year from p_periodo_fim) - extract(year from p_periodo_inicio)) * 12 + 
                                  extract(month from p_periodo_fim) - extract(month from p_periodo_inicio) + 1);

  -- Adições e exclusões (LALUR)
  v_lucro_ajustado_irpj := p_lucro_contabil_informado + p_adicoes_irpj - p_exclusoes_irpj;
  v_lucro_ajustado_csll := p_lucro_contabil_informado + p_adicoes_csll - p_exclusoes_csll;

  -- Compensação de Prejuízos Fiscais (trava dos 30% pela Lei 9.065/95)
  IF v_lucro_ajustado_irpj > 0 AND p_prejuizo_fiscal_acumulado_anterior > 0 THEN
    v_prejuizo_compensavel := v_lucro_ajustado_irpj * v_param.percentual_max_compensacao_prejuizo;
    v_prejuizo_compensado := least(p_prejuizo_fiscal_acumulado_anterior, v_prejuizo_compensavel);
  ELSE
    v_prejuizo_compensado := 0;
  END IF;

  v_prejuizo_remanescente := greatest(0, p_prejuizo_fiscal_acumulado_anterior - v_prejuizo_compensado);

  v_base_irpj := greatest(0, v_lucro_ajustado_irpj - v_prejuizo_compensado);
  v_base_csll := greatest(0, v_lucro_ajustado_csll - v_prejuizo_compensado);

  -- Cálculos IRPJ e Adicional
  v_irpj := v_base_irpj * v_param.aliquota_irpj;
  v_limite_adicional_periodo := v_param.limite_mensal_adicional * v_meses_periodo;
  IF v_base_irpj > v_limite_adicional_periodo THEN
    v_irpj_adicional := (v_base_irpj - v_limite_adicional_periodo) * v_param.aliquota_adicional_irpj;
  ELSE
    v_irpj_adicional := 0;
  END IF;

  v_csll := v_base_csll * v_param.aliquota_csll;

  -- Débitos PIS/COFINS Não-Cumulativos
  v_final_debito_pis := coalesce(p_debito_pis, p_receita_bruta_periodo * v_param.aliquota_pis_nao_cumulativo);
  v_final_debito_cofins := coalesce(p_debito_cofins, p_receita_bruta_periodo * v_param.aliquota_cofins_nao_cumulativo);

  v_pis_a_pagar := greatest(0, v_final_debito_pis - p_credito_pis);
  v_cofins_a_pagar := greatest(0, v_final_debito_cofins - p_credito_cofins);

  v_total_geral := v_irpj + v_irpj_adicional + v_csll + v_pis_a_pagar + v_cofins_a_pagar;

  -- Sinalização de revisão se créditos forem zerados (muito incomum no Lucro Real)
  IF p_credito_pis = 0 AND p_credito_cofins = 0 THEN
    v_status_revisao := 'pendente_revisao';
    v_motivo := 'Nenhum crédito de PIS/COFINS não-cumulativo foi informado para compensação do período.';
  END IF;

  IF p_gravar_memoria AND p_empresa_id IS NOT NULL THEN
    INSERT INTO lucro_real_memoria_calculo (
      empresa_id, periodo_inicio, periodo_fim, lucro_contabil_informado, informado_por,
      adicoes_irpj, exclusoes_irpj, adicoes_csll, exclusoes_csll, lucro_real_ajustado_irpj,
      lucro_real_ajustado_csll, prejuizo_fiscal_acumulado_anterior, prejuizo_compensado, prejuizo_fiscal_remanescente,
      base_irpj, irpj_valor, irpj_adicional, base_csll, csll_valor, receita_bruta_periodo,
      debito_pis, credito_pis, pis_a_pagar, debito_cofins, credito_cofins, cofins_a_pagar,
      total_geral_devido, status_revisao, motivo_revisao, usuario_id
    ) VALUES (
      p_empresa_id, p_periodo_inicio, p_periodo_fim, p_lucro_contabil_informado, p_informado_por,
      p_adicoes_irpj, p_exclusoes_irpj, p_adicoes_csll, p_exclusoes_csll, v_lucro_ajustado_irpj,
      v_lucro_ajustado_csll, p_prejuizo_fiscal_acumulado_anterior, v_prejuizo_compensado, v_prejuizo_remanescente,
      v_base_irpj, v_irpj, v_irpj_adicional, v_base_csll, v_csll, p_receita_bruta_periodo,
      v_final_debito_pis, p_credito_pis, v_pis_a_pagar, v_final_debito_cofins, p_credito_cofins, v_cofins_a_pagar,
      v_total_geral, v_status_revisao, v_motivo, p_usuario_id
    );
  END IF;

  RETURN jsonb_build_object(
    'periodo', jsonb_build_object('inicio', p_periodo_inicio, 'fim', p_periodo_fim, 'meses', v_meses_periodo),
    'lucro_contabil_informado', p_lucro_contabil_informado,
    'lucro_ajustado_irpj', v_lucro_ajustado_irpj,
    'prejuizo_fiscal', jsonb_build_object(
      'acumulado_anterior', p_prejuizo_fiscal_acumulado_anterior,
      'compensado_neste_periodo', round(v_prejuizo_compensado, 2),
      'remanescente', round(v_prejuizo_remanescente, 2),
      'trava_30pct_aplicada', v_param.percentual_max_compensacao_prejuizo
    ),
    'irpj', jsonb_build_object('base', round(v_base_irpj, 2), 'valor', round(v_irpj, 2), 'adicional', round(v_irpj_adicional, 2)),
    'csll', jsonb_build_object('base', round(v_base_csll, 2), 'valor', round(v_csll, 2)),
    'pis', jsonb_build_object('debito', round(v_final_debito_pis, 2), 'credito', p_credito_pis, 'a_pagar', round(v_pis_a_pagar, 2)),
    'cofins', jsonb_build_object('debito', round(v_final_debito_cofins, 2), 'credito', p_credito_cofins, 'a_pagar', round(v_cofins_a_pagar, 2)),
    'total_geral_devido', round(v_total_geral, 2),
    'status_revisao', v_status_revisao,
    'motivo_revisao', v_motivo,
    'fundamento_legal', v_param.fundamento_legal
  );
END;
$$;

-- [BLOCO 9/28/35] DIFAL Engine com Opção de Base Dupla e Proteção Negativa
CREATE OR REPLACE FUNCTION fn_calcular_difal(
  p_empresa_id UUID,
  p_uf_origem CHAR(2),
  p_uf_destino CHAR(2),
  p_valor_operacao NUMERIC,
  p_e_consumidor_final_nao_contribuinte BOOLEAN,
  p_documento_id UUID DEFAULT null,
  p_usuario_id UUID DEFAULT null,
  p_gravar_memoria BOOLEAN DEFAULT true,
  p_usar_base_dupla BOOLEAN DEFAULT false
) RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  v_aliquota_interna NUMERIC(5,2);
  v_aliquota_interestadual NUMERIC(5,2);
  v_base_difal NUMERIC(15,2);
  v_icms_interestadual NUMERIC(15,2);
  v_difal NUMERIC(15,2);
  v_fcp RECORD;
  v_fcp_valor NUMERIC(15,2) := 0;
  v_status TEXT := 'aprovado';
  v_motivo TEXT;
BEGIN
  IF p_uf_origem = p_uf_destino THEN
    RETURN jsonb_build_object('erro', 'DIFAL não se aplica a operações internas.');
  END IF;
  IF NOT p_e_consumidor_final_nao_contribuinte THEN
    RETURN jsonb_build_object(
      'aplica_difal', false,
      'motivo', 'DIFAL (EC 87/2015) aplica-se somente a vendas interestaduais para não-contribuintes.'
    );
  END IF;
  IF p_valor_operacao IS NULL OR p_valor_operacao <= 0 THEN
    RETURN jsonb_build_object('erro', 'Valor de operação inválido.');
  END IF;

  -- Busca alíquotas oficiais vigentes
  SELECT aliquota_interna INTO v_aliquota_interna FROM tabela_icms_uf WHERE uf = p_uf_destino AND status = 'vigente' LIMIT 1;
  
  -- Se houver interestadual direta
  v_aliquota_interestadual := CASE 
    WHEN p_uf_origem IN ('SP', 'RJ', 'MG', 'PR', 'RS', 'SC') AND p_uf_destino NOT IN ('SP', 'RJ', 'MG', 'PR', 'RS', 'SC') THEN 7.0
    ELSE 12.0
  END;

  IF v_aliquota_interna IS NULL THEN
    RETURN jsonb_build_object('erro', format('UF destino %s não possui alíquota cadastrada.', p_uf_destino));
  END IF;

  -- Proteção contra DIFAL negativo
  IF v_aliquota_interna <= v_aliquota_interestadual THEN
    RETURN jsonb_build_object(
      'aplica_difal', true,
      'difal_valor', 0,
      'total_recolher', 0,
      'status_revisao', 'pendente_revisao',
      'motivo_revisao', format('Alíquota interna destino (%s%%) menor ou igual à interestadual (%s%%). Cenário de DIFAL zerado por segurança.', v_aliquota_interna, v_aliquota_interestadual)
    );
  END IF;

  -- Base Dupla ou Base Simples
  IF p_usar_base_dupla THEN
    v_icms_interestadual := round(p_valor_operacao * (v_aliquota_interestadual / 100), 2);
    v_base_difal := round((p_valor_operacao - v_icms_interestadual) / (1 - (v_aliquota_interna / 100)), 2);
    v_difal := round((v_base_difal * (v_aliquota_interna / 100)) - v_icms_interestadual, 2);
    v_status := 'pendente_revisao';
    v_motivo := 'Cálculo realizado em base dupla. Confirme conformidade legal da UF de destino.';
  ELSE
    v_base_difal := p_valor_operacao;
    v_difal := round(v_base_difal * ((v_aliquota_interna - v_aliquota_interestadual) / 100), 2);
  END IF;

  -- FCP (Fundo Estadual Combate à Pobreza)
  SELECT * INTO v_fcp FROM tabela_fcp_uf WHERE uf = p_uf_destino;
  IF v_fcp IS NOT NULL AND v_fcp.possui_fcp THEN
    v_fcp_valor := round(v_base_difal * (v_fcp.aliquota_fcp_geral / 100), 2);
  END IF;

  IF p_gravar_memoria AND p_empresa_id IS NOT NULL THEN
    INSERT INTO difal_memoria_calculo (
      empresa_id, documento_id, uf_origem, uf_destino, valor_operacao, aliquota_interna_destino,
      aliquota_interestadual, base_difal, difal_valor, fcp_aliquota, fcp_valor, total_a_recolher_destino,
      status_revisao, motivo_revisao, usuario_id
    ) VALUES (
      p_empresa_id, p_documento_id, p_uf_origem, p_uf_destino, p_valor_operacao, v_aliquota_interna,
      v_aliquota_interestadual, v_base_difal, v_difal, coalesce(v_fcp.aliquota_fcp_geral, 0), v_fcp_valor, v_difal + v_fcp_valor,
      v_status, v_motivo, p_usuario_id
    );
  END IF;

  RETURN jsonb_build_object(
    'aplica_difal', true,
    'uf_origem', p_uf_origem,
    'uf_destino', p_uf_destino,
    'valor_operacao', p_valor_operacao,
    'usou_base_dupla', p_usar_base_dupla,
    'base_difal', v_base_difal,
    'aliquota_interna_destino_pct', v_aliquota_interna,
    'aliquota_interestadual_pct', v_aliquota_interestadual,
    'difal_valor', round(v_difal, 2),
    'fcp_valor', round(v_fcp_valor, 2),
    'total_recolher', round(v_difal + v_fcp_valor, 2),
    'status_revisao', v_status,
    'motivo_revisao', v_motivo,
    'fundamento_legal', 'EC 87/2015; LC 190/2022 (DIFAL Não Contribuinte)'
  );
END;
$$;

-- [BLOCO 37] SUÍTE DE TESTES AUTOMATIZADOS (VERIFICAÇÃO COMPLETA DO MOTOR)
CREATE OR REPLACE FUNCTION fn_rodar_testes_motor_fiscal()
RETURNS TABLE (
  teste TEXT,
  esperado TEXT,
  obtido TEXT,
  passou BOOLEAN
) LANGUAGE plpgsql AS $$
DECLARE
  v_resultado JSONB;
BEGIN
  -- Teste 1: Simples Nacional Faixa 2 Anexo III
  v_resultado := fn_calcular_simples_nacional('III', 200000.00, 10000.00, p_gravar_memoria := false);
  teste := 'Simples Nacional - Faixa 2 - Anexo III';
  esperado := '6.520000';
  obtido := coalesce(v_resultado ->> 'aliquota_efetiva', '0.00');
  passou := (obtido::numeric = 0.065200);
  RETURN NEXT;

  -- Teste 2: MEI Comércio DAS
  v_resultado := fn_calcular_mei(NULL, '2026-06-01', 'comercio_industria', 5000.00, '2026-01-01', 35000.00, p_gravar_memoria := false);
  teste := 'MEI - Comércio DAS 2026';
  esperado := '82.05';
  obtido := coalesce(v_resultado ->> 'das_devido', '0.00');
  passou := (obtido::numeric = 82.05);
  RETURN NEXT;

  -- Teste 3: Lucro Presumido IRPJ Comercio
  v_resultado := fn_calcular_lucro_presumido(NULL, '2026-06-01', 'comercio', 50000.00, true, 'SP', 'SP', p_gravar_memoria := false);
  teste := 'Lucro Presumido - IRPJ Comércio (0.08 * 0.15 = 1.2%)';
  esperado := '600.00';
  obtido := coalesce(v_resultado -> 'irpj' ->> 'valor', '0.00');
  passou := (obtido::numeric = 600.00);
  RETURN NEXT;
END;
$$;

-- ==============================================================================
-- PARTE 10: PROCEDIMENTOS NATIVOS DE CARGA E LEITURA DE XML (XPATH) (BLOCOS 10, 18, 19, 20)
-- ==============================================================================

-- [BLOCO 18/19/20] Leitura de Tags XML para NF-e (55), NFC-e (65), CT-e (57) e MDF-e (58)
CREATE OR REPLACE FUNCTION fn_identificar_modelo_documento_xml(p_xml_content TEXT)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
  v_doc XML;
  v_ns TEXT[][] := ARRAY[ARRAY['nfe', 'http://www.portalfiscal.inf.br/nfe']];
  v_modelo TEXT;
  v_tipo_documento TEXT;
BEGIN
  BEGIN
    v_doc := xmlparse(document p_xml_content);
  EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('erro', 'XML inválido ou malformado.');
  END;

  v_modelo := (xpath('//nfe:ide/nfe:mod/text()', v_doc, v_ns))[1]::text;
  v_tipo_documento := CASE 
    WHEN v_modelo = '55' THEN 'NF-e'
    WHEN v_modelo = '65' THEN 'NFC-e'
    WHEN v_modelo = '57' THEN 'CT-e'
    WHEN v_modelo = '58' THEN 'MDF-e'
    ELSE 'Desconhecido'
  END;

  RETURN jsonb_build_object(
    'modelo', v_modelo,
    'tipo_documento', v_tipo_documento,
    'reconhecido', v_modelo IN ('55', '65', '57', '58')
  );
END;
$$;

-- ==============================================================================
-- COMPLEMENTOS FINAIS E CRON DE LIMPEZA DE CACHE
-- ==============================================================================

CREATE OR REPLACE FUNCTION fn_limpar_cache_calculo()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_removidos INT;
BEGIN
  DELETE FROM cache_calculo_tributario WHERE expires_at < now();
  GET DIAGNOSTICS v_removidos = row_count;
  RETURN jsonb_build_object('removidos', v_removidos, 'executado_em', now());
END;
$$;

-- FIM DO SCRIPT UNIFICADO CONSOLIDADO CÂMERA FISCAL
-- ==============================================================================
